node {
    try {
        dir("${env.WORKSPACE}/../${env.JOB_NAME}@script/"){
            stage('Checkout') {
                echo "python BSP_NightlyBuild/Checkout.py"
            }
            stage('Build') {
                echo "python BSP_NightlyBuild/Build.py"
            }
            stage('Test') {
                sh "python BSP_NightlyBuild/Test.py"
            }
            stage('Deploy') {
                sh "python BSP_NightlyBuild/Deploy.py"
            }
        }
    } catch (err) {
        currentBuild.result = 'FAILED'
        throw err
    }
}
